services:
  - type: web
    name: painting-progress
    env: node
    plan: starter
    rootDir: Painting Progress
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
